### ISSUE TITLE
[BE] Feat: Data 뷰 렌더링

### ISSUE THREAD

**Issue by toychip** [toychip/MailValidation#5]
# TODO

- [x] 데이터 view 렌더링
- [x] 데이터 exel 다운로드
- [x] db가 아닌 입력한 값을 검증 후 다운로드 및 렌더링해야함
